UPDATE misuse_reports SET city = NULL, state = 'SC', lat = 34.0007, lon = -81.0348, department = NULL, location_precision = 'state', cluster_id = 1 WHERE id = 1;
UPDATE misuse_reports SET city = 'Racine', state = 'WI', lat = 42.7261, lon = -87.7829, department = NULL, location_precision = 'city', cluster_id = 2 WHERE id = 2;
UPDATE misuse_reports SET city = NULL, state = NULL, lat = 39.8283, lon = -98.5795, department = NULL, location_precision = 'unknown', cluster_id = 3 WHERE id = 3;
UPDATE misuse_reports SET city = 'Milwaukee', state = 'WI', lat = 43.0389, lon = -87.9065, department = NULL, location_precision = 'city', cluster_id = 4 WHERE id = 4;
UPDATE misuse_reports SET city = NULL, state = 'SC', lat = 34.0007, lon = -81.0348, department = NULL, location_precision = 'state', cluster_id = 5 WHERE id = 5;
UPDATE misuse_reports SET city = NULL, state = NULL, lat = 39.8283, lon = -98.5795, department = NULL, location_precision = 'unknown', cluster_id = 6 WHERE id = 6;
UPDATE misuse_reports SET city = 'Racine', state = 'WI', lat = 42.7261, lon = -87.7829, department = NULL, location_precision = 'city', cluster_id = 7 WHERE id = 7;
UPDATE misuse_reports SET city = 'Racine', state = 'WI', lat = 42.7261, lon = -87.7829, department = NULL, location_precision = 'city', cluster_id = 8 WHERE id = 8;
UPDATE misuse_reports SET city = 'Pasadena', state = 'TX', lat = 29.6911, lon = -95.2091, department = NULL, location_precision = 'city', cluster_id = 10 WHERE id = 9;
UPDATE misuse_reports SET city = 'Pasadena', state = 'TX', lat = 29.6911, lon = -95.2091, department = NULL, location_precision = 'city', cluster_id = 10 WHERE id = 10;
UPDATE misuse_reports SET city = NULL, state = 'GA', lat = 33.749, lon = -84.388, department = NULL, location_precision = 'state', cluster_id = 11 WHERE id = 11;
UPDATE misuse_reports SET city = 'Milwaukee', state = 'WI', lat = 43.0389, lon = -87.9065, department = 'Milwaukee Police Department', location_precision = 'city', cluster_id = 12 WHERE id = 12;
UPDATE misuse_reports SET city = 'Milwaukee', state = 'WI', lat = 43.0389, lon = -87.9065, department = NULL, location_precision = 'city', cluster_id = 13 WHERE id = 13;
UPDATE misuse_reports SET city = NULL, state = 'GA', lat = 33.749, lon = -84.388, department = NULL, location_precision = 'state', cluster_id = 14 WHERE id = 14;
UPDATE misuse_reports SET city = NULL, state = NULL, lat = 39.8283, lon = -98.5795, department = NULL, location_precision = 'unknown', cluster_id = 15 WHERE id = 15;
UPDATE misuse_reports SET city = NULL, state = NULL, lat = 39.8283, lon = -98.5795, department = NULL, location_precision = 'unknown', cluster_id = 16 WHERE id = 16;
UPDATE misuse_reports SET city = NULL, state = NULL, lat = 39.8283, lon = -98.5795, department = NULL, location_precision = 'unknown', cluster_id = 17 WHERE id = 17;
UPDATE misuse_reports SET city = NULL, state = NULL, lat = 39.8283, lon = -98.5795, department = NULL, location_precision = 'unknown', cluster_id = 18 WHERE id = 18;
UPDATE misuse_reports SET city = 'San Francisco', state = 'CA', lat = 37.7749, lon = -122.4194, department = NULL, location_precision = 'city', cluster_id = 19 WHERE id = 19;
UPDATE misuse_reports SET city = 'Boulder', state = 'CO', lat = 40.015, lon = -105.2705, department = NULL, location_precision = 'city', cluster_id = 20 WHERE id = 20;
UPDATE misuse_reports SET city = 'Fargo', state = 'ND', lat = 46.8772, lon = -96.7898, department = NULL, location_precision = 'city', cluster_id = 21 WHERE id = 21;
UPDATE misuse_reports SET city = 'Milwaukee', state = 'WI', lat = 43.0389, lon = -87.9065, department = NULL, location_precision = 'city', cluster_id = 22 WHERE id = 22;
UPDATE misuse_reports SET city = 'Milwaukee', state = 'WI', lat = 43.0389, lon = -87.9065, department = NULL, location_precision = 'city', cluster_id = 23 WHERE id = 23;
UPDATE misuse_reports SET city = 'Boulder', state = 'CO', lat = 40.015, lon = -105.2705, department = NULL, location_precision = 'city', cluster_id = 24 WHERE id = 24;
UPDATE misuse_reports SET city = 'Milwaukee', state = 'WI', lat = 43.0389, lon = -87.9065, department = NULL, location_precision = 'city', cluster_id = 25 WHERE id = 25;
UPDATE misuse_reports SET city = 'Milwaukee', state = 'WI', lat = 43.0389, lon = -87.9065, department = NULL, location_precision = 'city', cluster_id = 26 WHERE id = 26;
UPDATE misuse_reports SET city = NULL, state = NULL, lat = 39.8283, lon = -98.5795, department = NULL, location_precision = 'unknown', cluster_id = 27 WHERE id = 27;
UPDATE misuse_reports SET city = 'Richmond', state = 'VA', lat = 37.5407, lon = -77.436, department = NULL, location_precision = 'city', cluster_id = 28 WHERE id = 28;
UPDATE misuse_reports SET city = 'Mesa', state = 'AZ', lat = 33.4152, lon = -111.8315, department = NULL, location_precision = 'city', cluster_id = 29 WHERE id = 29;
UPDATE misuse_reports SET city = NULL, state = NULL, lat = 39.8283, lon = -98.5795, department = NULL, location_precision = 'unknown', cluster_id = 30 WHERE id = 30;
UPDATE misuse_reports SET city = 'Pasadena', state = 'TX', lat = 29.6911, lon = -95.2091, department = 'Pasadena Police', location_precision = 'city', cluster_id = 31 WHERE id = 31;
UPDATE misuse_reports SET city = NULL, state = 'WI', lat = 43.0731, lon = -89.4012, department = NULL, location_precision = 'state', cluster_id = 32 WHERE id = 32;
UPDATE misuse_reports SET city = 'Milwaukee', state = 'WI', lat = 43.0389, lon = -87.9065, department = 'Milwaukee Police', location_precision = 'city', cluster_id = 33 WHERE id = 33;
UPDATE misuse_reports SET city = NULL, state = 'VA', lat = 37.5407, lon = -77.436, department = NULL, location_precision = 'state', cluster_id = 34 WHERE id = 34;
UPDATE misuse_reports SET city = NULL, state = 'VA', lat = 37.5407, lon = -77.436, department = NULL, location_precision = 'state', cluster_id = 35 WHERE id = 35;
UPDATE misuse_reports SET city = 'Milwaukee', state = 'WI', lat = 43.0389, lon = -87.9065, department = NULL, location_precision = 'city', cluster_id = 36 WHERE id = 36;
UPDATE misuse_reports SET city = 'Mountain View', state = 'CA', lat = 37.3861, lon = -122.0839, department = NULL, location_precision = 'city', cluster_id = 37 WHERE id = 37;
UPDATE misuse_reports SET city = NULL, state = NULL, lat = 39.8283, lon = -98.5795, department = NULL, location_precision = 'unknown', cluster_id = 38 WHERE id = 38;
UPDATE misuse_reports SET city = NULL, state = 'GA', lat = 33.749, lon = -84.388, department = NULL, location_precision = 'state', cluster_id = 39 WHERE id = 39;
UPDATE misuse_reports SET city = NULL, state = NULL, lat = 39.8283, lon = -98.5795, department = NULL, location_precision = 'unknown', cluster_id = 40 WHERE id = 40;
UPDATE misuse_reports SET city = 'DeKalb', state = 'IL', lat = 41.9295, lon = -88.7504, department = NULL, location_precision = 'city', cluster_id = 41 WHERE id = 41;
UPDATE misuse_reports SET city = 'Oakley', state = 'CA', lat = 37.9974, lon = -121.7125, department = 'Oakley Police', location_precision = 'city', cluster_id = 42 WHERE id = 42;
UPDATE misuse_reports SET city = 'Los Angeles', state = 'CA', lat = 34.0522, lon = -118.2437, department = 'Los Angeles Police Department', location_precision = 'city', cluster_id = 43 WHERE id = 43;
UPDATE misuse_reports SET city = 'Los Angeles', state = 'CA', lat = 34.0522, lon = -118.2437, department = 'Los Angeles Police Department', location_precision = 'city', cluster_id = 44 WHERE id = 44;
UPDATE misuse_reports SET city = 'Los Angeles', state = 'CA', lat = 34.0522, lon = -118.2437, department = 'Los Angeles Police Department', location_precision = 'city', cluster_id = 45 WHERE id = 45;
UPDATE misuse_reports SET city = 'Los Angeles', state = 'CA', lat = 34.0522, lon = -118.2437, department = 'Los Angeles Police Department', location_precision = 'city', cluster_id = 46 WHERE id = 46;
UPDATE misuse_reports SET city = 'Westland', state = 'MI', lat = 42.3242, lon = -83.4002, department = NULL, location_precision = 'city', cluster_id = 48 WHERE id = 48;
UPDATE misuse_reports SET city = NULL, state = 'GA', lat = 33.749, lon = -84.388, department = NULL, location_precision = 'state', cluster_id = 50 WHERE id = 50;
UPDATE misuse_reports SET city = 'Madison', state = 'WI', lat = 43.0731, lon = -89.4012, department = NULL, location_precision = 'city', cluster_id = 53 WHERE id = 53;
UPDATE misuse_reports SET city = 'Fargo', state = 'ND', lat = 46.8772, lon = -96.7898, department = 'Fargo Police', location_precision = 'city', cluster_id = 54 WHERE id = 54;
UPDATE misuse_reports SET city = NULL, state = 'GA', lat = 33.749, lon = -84.388, department = NULL, location_precision = 'state', cluster_id = 55 WHERE id = 55;
UPDATE misuse_reports SET city = NULL, state = NULL, lat = 39.8283, lon = -98.5795, department = NULL, location_precision = 'unknown', cluster_id = 56 WHERE id = 56;
UPDATE misuse_reports SET city = 'DeKalb', state = 'IL', lat = 41.9295, lon = -88.7504, department = NULL, location_precision = 'city', cluster_id = 59 WHERE id = 57;
UPDATE misuse_reports SET city = 'DeKalb', state = 'IL', lat = 41.9295, lon = -88.7504, department = NULL, location_precision = 'city', cluster_id = 59 WHERE id = 59;
UPDATE misuse_reports SET city = 'San Francisco', state = 'CA', lat = 37.7749, lon = -122.4194, department = NULL, location_precision = 'city', cluster_id = 60 WHERE id = 60;
UPDATE misuse_reports SET city = NULL, state = NULL, lat = 39.8283, lon = -98.5795, department = NULL, location_precision = 'unknown', cluster_id = 62 WHERE id = 62;
UPDATE misuse_reports SET city = 'Boulder', state = 'CO', lat = 40.015, lon = -105.2705, department = NULL, location_precision = 'city', cluster_id = 64 WHERE id = 64;
UPDATE misuse_reports SET city = 'Boulder', state = 'CO', lat = 40.015, lon = -105.2705, department = NULL, location_precision = 'city', cluster_id = 64 WHERE id = 66;
UPDATE misuse_reports SET city = NULL, state = NULL, lat = 39.8283, lon = -98.5795, department = NULL, location_precision = 'unknown', cluster_id = 67 WHERE id = 67;
UPDATE misuse_reports SET city = 'Green Bay', state = 'WI', lat = 44.5192, lon = -88.0198, department = NULL, location_precision = 'city', cluster_id = 68 WHERE id = 68;
UPDATE misuse_reports SET city = NULL, state = NULL, lat = 39.8283, lon = -98.5795, department = NULL, location_precision = 'unknown', cluster_id = 69 WHERE id = 69;
UPDATE misuse_reports SET city = NULL, state = NULL, lat = 39.8283, lon = -98.5795, department = NULL, location_precision = 'unknown', cluster_id = 70 WHERE id = 70;
UPDATE misuse_reports SET city = NULL, state = 'WA', lat = 47.0379, lon = -122.9007, department = NULL, location_precision = 'state', cluster_id = 71 WHERE id = 71;
UPDATE misuse_reports SET city = 'Antioch', state = 'CA', lat = 38.0049, lon = -121.8058, department = NULL, location_precision = 'city', cluster_id = 73 WHERE id = 73;
UPDATE misuse_reports SET city = NULL, state = 'TX', lat = 30.2672, lon = -97.7431, department = NULL, location_precision = 'state', cluster_id = 74 WHERE id = 74;
UPDATE misuse_reports SET city = 'Dunwoody', state = 'GA', lat = 33.9462, lon = -84.3346, department = NULL, location_precision = 'city', cluster_id = 75 WHERE id = 75;
UPDATE misuse_reports SET city = NULL, state = NULL, lat = 39.8283, lon = -98.5795, department = NULL, location_precision = 'unknown', cluster_id = 76 WHERE id = 76;
UPDATE misuse_reports SET city = 'Vallejo', state = 'CA', lat = 38.1041, lon = -122.2566, department = NULL, location_precision = 'city', cluster_id = 77 WHERE id = 77;
UPDATE misuse_reports SET city = 'DeKalb', state = 'IL', lat = 41.9295, lon = -88.7504, department = NULL, location_precision = 'city', cluster_id = 81 WHERE id = 81;
UPDATE misuse_reports SET city = 'Florida', state = 'NY', lat = 41.3295, lon = -74.3528, department = 'Florida Police', location_precision = 'city', cluster_id = 83 WHERE id = 83;
UPDATE misuse_reports SET city = 'Richmond', state = 'VA', lat = 37.5407, lon = -77.436, department = NULL, location_precision = 'city', cluster_id = 89 WHERE id = 89;
UPDATE misuse_reports SET city = 'Mansfield', state = 'TX', lat = 32.5632, lon = -97.1417, department = NULL, location_precision = 'city', cluster_id = 95 WHERE id = 95;
UPDATE misuse_reports SET city = NULL, state = NULL, lat = 39.8283, lon = -98.5795, department = NULL, location_precision = 'unknown', cluster_id = 96 WHERE id = 96;
UPDATE misuse_reports SET city = 'Richmond', state = 'VA', lat = 37.5407, lon = -77.436, department = NULL, location_precision = 'city', cluster_id = 101 WHERE id = 101;
UPDATE misuse_reports SET city = 'Merced', state = 'CA', lat = 37.3022, lon = -120.483, department = 'Merced Police', location_precision = 'city', cluster_id = 105 WHERE id = 105;
UPDATE misuse_reports SET city = 'Gary', state = 'IN', lat = 41.5934, lon = -87.3464, department = NULL, location_precision = 'city', cluster_id = 106 WHERE id = 106;
UPDATE misuse_reports SET city = NULL, state = NULL, lat = 39.8283, lon = -98.5795, department = NULL, location_precision = 'unknown', cluster_id = 108 WHERE id = 108;
UPDATE misuse_reports SET city = NULL, state = NULL, lat = 39.8283, lon = -98.5795, department = NULL, location_precision = 'unknown', cluster_id = 109 WHERE id = 109;
